#!/usr/bin/env bash

set -Eeuxo pipefail

rootfs=$1
targetBase=$2
targetBaseDir=$(dirname "$targetBase")
timestamp=$(garden-version --epoch "$version")

apt-get update
apt-get install -y curl
echo 'deb http://download.opensuse.org/repositories/home:/jepio:/flatcar/Debian_Testing/ /' | tee /etc/apt/sources.list.d/home:jepio:flatcar.list
curl -fsSL https://download.opensuse.org/repositories/home:jepio:flatcar/Debian_Testing/Release.key | gpg --dearmor | tee /etc/apt/trusted.gpg.d/home_jepio_flatcar.gpg > /dev/null
apt-get update
apt-get install -y update-engine

efipart=$(sfdisk --dump ${targetBase}.raw | grep ${targetBase}.raw1)
usrpart=$(sfdisk --dump ${targetBase}.raw | grep ${targetBase}.raw3)
efistart=$(echo $efipart | sed -e 's/.*start= *\([^,]*\), .*/\1/')
efisize=$(echo $efipart | sed -e 's/.*size= *\([^,]*\), .*/\1/')
usrstart=$(echo $usrpart | sed -e 's/.*start= *\([^,]*\), .*/\1/')
usrsize=$(echo $usrpart | sed -e 's/.*size= *\([^,]*\), .*/\1/')

rootfs_work=$(mktemp -d)
dd if=${targetBase}.raw bs=512 skip=$efistart count=$efisize of=${rootfs_work}/efi.raw
dd if=${targetBase}.raw bs=512 skip=$usrstart count=$usrsize of=${rootfs_work}/usr.raw

mcopy -i ${rootfs_work}/efi.raw ::/EFI/BOOT/BOOTX64.EFI ${rootfs_work}/GARDEN.EFI

delta_generator -new_image ${rootfs_work}/usr.raw -new_kernel ${rootfs_work}/GARDEN.EFI -private_key "$rootfs"/usr/share/update_engine/update-payload-key.key.pem -out_file ${targetBase}.update.gz
cp "$rootfs"/usr/share/update_engine/update-payload-key.pub.pem ${targetBaseDir}/update-payload-key.pub.pem

rm -rf ${rootfs_work}
